/// Log tag definitions for module categorization
///
/// This is moved from logger.rs to keep the module organized.
/// Tags identify which part of the system is logging.
use colored::*;

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum LogTag {
    Monitor,
    Trader,
    Wallet,
    System,
    Connectivity,
    Pool,
    PoolService,
    PoolCalculator,
    PoolDiscovery,
    PoolFetcher,
    PoolAnalyzer,
    PoolCache,
    PoolDecoder,
    Blacklist,
    Discovery,
    Filtering,
    Api,
    Profit,
    PriceService,
    SolPrice,
    Rpc,
    Ohlcv,
    Decimals,
    Cache,
    Swap,
    Entry,
    RlLearn,
    Summary,
    Tokens,
    Transactions,
    Websocket,
    Positions,
    Security,
    Webserver,
    Test,
    Other(String),
}

impl LogTag {
    /// Convert tag to debug key for config lookup
    pub fn to_debug_key(&self) -> String {
        match self {
            LogTag::Monitor => "monitor".to_string(),
            LogTag::Trader => "trader".to_string(),
            LogTag::Wallet => "wallet".to_string(),
            LogTag::System => "system".to_string(),
            LogTag::Connectivity => "connectivity".to_string(),
            LogTag::Pool => "pool".to_string(),
            LogTag::PoolService => "pool_service".to_string(),
            LogTag::PoolCalculator => "pool_calculator".to_string(),
            LogTag::PoolDiscovery => "pool_discovery".to_string(),
            LogTag::PoolFetcher => "pool_fetcher".to_string(),
            LogTag::PoolAnalyzer => "pool_analyzer".to_string(),
            LogTag::PoolCache => "pool_cache".to_string(),
            LogTag::PoolDecoder => "pool_decoder".to_string(),
            LogTag::Blacklist => "blacklist".to_string(),
            LogTag::Discovery => "discovery".to_string(),
            LogTag::Filtering => "filtering".to_string(),
            LogTag::Api => "api".to_string(),
            LogTag::Profit => "profit".to_string(),
            LogTag::PriceService => "price_service".to_string(),
            LogTag::SolPrice => "sol_price".to_string(),
            LogTag::Rpc => "rpc".to_string(),
            LogTag::Ohlcv => "ohlcv".to_string(),
            LogTag::Decimals => "decimals".to_string(),
            LogTag::Cache => "cache".to_string(),
            LogTag::Swap => "swap".to_string(),
            LogTag::Entry => "entry".to_string(),
            LogTag::RlLearn => "rl_learn".to_string(),
            LogTag::Summary => "summary".to_string(),
            LogTag::Tokens => "tokens".to_string(),
            LogTag::Transactions => "transactions".to_string(),
            LogTag::Websocket => "websocket".to_string(),
            LogTag::Positions => "positions".to_string(),
            LogTag::Security => "security".to_string(),
            LogTag::Webserver => "webserver".to_string(),
            LogTag::Test => "test".to_string(),
            LogTag::Other(ref s) => s.to_lowercase(),
        }
    }

    /// Get plain text representation (for file logging)
    pub fn to_plain_string(&self) -> &'static str {
        match self {
            LogTag::Monitor => "MONITOR",
            LogTag::Trader => "TRADER",
            LogTag::Wallet => "WALLET",
            LogTag::System => "SYSTEM",
            LogTag::Connectivity => "CONNECT",
            LogTag::Pool => "POOL",
            LogTag::PoolService => "POOLSVC",
            LogTag::PoolCalculator => "POOLCALC",
            LogTag::PoolDiscovery => "POOLDISC",
            LogTag::PoolFetcher => "POOLFETCH",
            LogTag::PoolAnalyzer => "POOLANLZ",
            LogTag::PoolCache => "POOLCACH",
            LogTag::PoolDecoder => "POOLDEC",
            LogTag::Blacklist => "BLACKLIST",
            LogTag::Discovery => "DISCOVER",
            LogTag::Filtering => "FILTER",
            LogTag::Api => "API",
            LogTag::Profit => "PROFIT",
            LogTag::PriceService => "PRICE",
            LogTag::SolPrice => "SOLPRICE",
            LogTag::Rpc => "RPC",
            LogTag::Ohlcv => "OHLCV",
            LogTag::Decimals => "DECIMALS",
            LogTag::Cache => "CACHE",
            LogTag::Swap => "SWAP",
            LogTag::Entry => "ENTRY",
            LogTag::RlLearn => "RL_LEARN",
            LogTag::Summary => "SUMMARY",
            LogTag::Tokens => "TOKENS",
            LogTag::Transactions => "TX",
            LogTag::Websocket => "WS",
            LogTag::Positions => "Positions",
            LogTag::Security => "SECURITY",
            LogTag::Webserver => "WEBSERVER",
            LogTag::Test => "TEST",
            LogTag::Other(_) => "OTHER",
        }
    }
}

impl std::fmt::Display for LogTag {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let tag_str = match self {
            LogTag::Monitor => format!("{:<8}", "MONITOR").bright_cyan().bold(),
            LogTag::Trader => format!("{:<8}", "TRADER").bright_blue().bold(),
            LogTag::Wallet => format!("{:<8}", "WALLET").bright_magenta().bold(),
            LogTag::System => format!("{:<8}", "SYSTEM").bright_yellow().bold(),
            LogTag::Connectivity => format!("{:<8}", "CONNECT").bright_green().bold(),
            LogTag::Pool => format!("{:<8}", "POOL").bright_blue().bold(),
            LogTag::PoolService => format!("{:<8}", "POOLSVC").bright_cyan().bold(),
            LogTag::PoolCalculator => format!("{:<8}", "POOLCALC").bright_green().bold(),
            LogTag::PoolDiscovery => format!("{:<8}", "POOLDISC").bright_white().bold(),
            LogTag::PoolFetcher => format!("{:<8}", "POOLFETCH").bright_yellow().bold(),
            LogTag::PoolAnalyzer => format!("{:<8}", "POOLANLZ").bright_magenta().bold(),
            LogTag::PoolCache => format!("{:<8}", "POOLCACH").bright_cyan().bold(),
            LogTag::PoolDecoder => format!("{:<8}", "POOLDEC").bright_blue().bold(),
            LogTag::Blacklist => format!("{:<8}", "BLACKLIST").bright_red().bold(),
            LogTag::Discovery => format!("{:<8}", "DISCOVER").bright_white().bold(),
            LogTag::Filtering => format!("{:<8}", "FILTER").bright_yellow().bold(),
            LogTag::Api => format!("{:<8}", "API").bright_purple().bold(),
            LogTag::Profit => format!("{:<8}", "PROFIT").bright_purple().bold(),
            LogTag::PriceService => format!("{:<8}", "PRICE").bright_green().bold(),
            LogTag::SolPrice => format!("{:<8}", "SOLPRICE").bright_yellow().bold(),
            LogTag::Rpc => format!("{:<8}", "RPC").bright_cyan().bold(),
            LogTag::Ohlcv => format!("{:<8}", "OHLCV").bright_green().bold(),
            LogTag::Decimals => format!("{:<8}", "DECIMALS").bright_white().bold(),
            LogTag::Cache => format!("{:<8}", "CACHE").bright_cyan().bold(),
            LogTag::Swap => format!("{:<8}", "SWAP").bright_magenta().bold(),
            LogTag::Entry => format!("{:<8}", "ENTRY").bright_yellow().bold(),
            LogTag::RlLearn => format!("{:<8}", "RL_LEARN").bright_cyan().bold(),
            LogTag::Summary => format!("{:<8}", "SUMMARY").bright_white().bold(),
            LogTag::Tokens => format!("{:<8}", "TOKENS").bright_cyan().bold(),
            LogTag::Transactions => format!("{:<8}", "TX").bright_blue().bold(),
            LogTag::Websocket => format!("{:<8}", "WS").bright_cyan().bold(),
            LogTag::Positions => format!("{:<8}", "Positions").bright_yellow().bold(),
            LogTag::Security => format!("{:<8}", "SECURITY").bright_red().bold(),
            LogTag::Webserver => format!("{:<8}", "WEBSERVER").bright_green().bold(),
            LogTag::Test => format!("{:<8}", "TEST").bright_blue().bold(),
            LogTag::Other(s) => format!("{:<8}", s).white().bold(),
        };
        write!(f, "{}", tag_str)
    }
}
